---
title: "Materials and methods - Single cell analysis"
format:
  docx
bibliography: 
  references.bib
link-bibliography: true
linkcolor: blue
---

# Code availability
The code used for the analysis of the single cell RNA sequencing and TCR sequencing data is available at: https://github.com/EduardAnsaldo/202507_lung_Abau_Ftul_CT_MAIT_Dom

TO BE MADE PUBLIC UPON PUBLICATION OR SHARED UPON REQUEST BY THE REVIEWERS

# Methods

## Single-cell RNA sequencing and TCR sequencing of MAIT cells

MAIT cells were single cell sorted as TCRβ+, MR1:5-OP-RU tetramer+ from 4 uninfected PLACEHOLDER mice, 5 mice 7 DPI *F. tularensis*, or 4 mice 7 DPI *A. baumannii* on Thermo Fisher Scientific Bigfoot. Prior to sorting, individual samples within each group were labelled with TotalSeq-C hashtag antibodies (Biolegend) for sample multiplexing. Each group was loaded onto a separate 10x lane and single cell RNAseq libraries were generated utilizing 10x Genomics manufacturer recommendations by the Scripps Research Genomics core. The gene expression (GEX), hashtag oligonucleotide (HTO) and VDJ (TCR) sequencing libraries were prepared using Chromium Single Cell 5’ v2 reagent kits following the manufacturer’s instructions. The initial processing of the expression data involved generating fastq files and count matrices using Cell Ranger v9.0.1 [@zheng2017] (10X Genomics, Pleasanton, CA) that was run with the “Include introns=True” option and the GRCm39-2024-A transcriptome reference. The TCR data was processed with Cell Ranger v9.0.1 using a VDJ reference available from 10x Genomics (refdata-cellranger-vdj-GRCm38-alts-ensembl-7.0.0). Processing of the expression data was performed with the 'cellranger multi' and 'cellranger aggr' functions. After processing and aggregation, the estimated number of cells and mean reads per cell for each library were as follows: 23204 estimated number of cells, 33348 mean reads per cell (from 3 GEX libraries), 4140 mean hashtag reads per Cell (across 3 HTO libraries), 11394 cells with a productive TRA and TRB V-J spanning pair (from 3 VDJ libraries). The overall sequencing quality was high in all libraries: \>92.7% of bases had Q30 (99.99% inferred base call accuracy, mean 95.0%) quality score or above. Furthermore, across the 3 GEX libraries the median UMI count per cell was 5600, and and the median gene count per cell was 2145. 

The downstream analysis of the expression data was performed in R 4.5.1, the Cell Ranger aggregation output (filtered_feature_bc_matrix directory) was loaded into Seurat version 5.3.0 [@hao2021]. Data were split into individual lanes and preprocessed separately: For filtering out low-quality cells, we established maximum thresholds for gene and UMI counts and a maximum threshold for percentage mitochondrial content based on visual inspection of the corresponding metric distributions across all cells. HTO count data were normalized by centered log-ratio transformation (CLR). For HTO demultiplexing cells into the individual mice and removing doublets, HTODemux was run with a positive quantile = 0.99 and only cells identified as Singlets were kept. After preprocessing, all three samples were merged together and normalization of the RNA count data was performed using SCTransform [@choudharyComparisonEvaluationStatistical2022]. The top 3000 variable features were used for dimensionality reduction by PCA, followed by determining the dimensionality of the dataset on an elbow plot (ElbowPlot function), which was determined to be 25. Subsequently, FindNeighbors, FindClusters, and RunUMAP were run on 25 dimensions and a range of resolutions to determine the optimal resolution that captures biological diversity in the dataset, which was determined to be 0.375. The clusters identified by the FindClusters function of Seurat (Leiden clustering and 0.25 resolution) were annotated using cell type specific markers, cluster specific differentially expressed genes, and with the aid of SingleR [@aran2019], using the ImmGen database reference. Contaminating clusters comprised of Macrophages were removed. On the remaining cells data normalization and clustering as described above were rerun with the same parameters, with the addition of removal of any VDJ segment genes from the valuable feature set to prevent clustering based on clonal expansions. One additional round of QC using DropletQC [@muskovicDropletQCImprovedIdentification2021] identified a distinct cluster as being comprised of damaged cells, which were removed. After two rounds of QC data normalization and clustering was performed as described above, with 25 dimensions and resolution of 0.625. Cell cycle scoring was performed using Seurat, and upon identifying that clustering was mostly driven by cell cycle, an additional round of data normalization and clustering was performed with regression of cell cycle scores during the SCTransform step, using the vars.to.regress parameter. The final clustering was performed with 30 dimensions and a resolution of 0.375. Clustering of the separate *A. baumannii* and *F. tularensis* subsets was performed as described above, without cell cycle regression, using 15 dimensions for both subsets and resolutions of 0.5 and 0.625, respectively.

Previously published gene lists [@duhalgouetRoleMR1drivenSignals2023; @linehanNonclassicalImmunityControls2018]. were used to determine signature scores with the “UCell” package [@andreattaUCellRobustScalable2021]. Pseudobulk analysis on CD4^+^T-bet^+^Foxp3^-^ T cells with the indicated comparisons was performed as described in the corresponding methods section with a log2(FC threshold) of 1 and an adjusted p value threshold of 0.05. Pseudobulk analysis with the indicated comparisons was performed as described in the corresponding methods with a FC threshold of 0.3 and an adjusted p value threshold of 0.05. Pathway enrichment analysis of upregulated or downregulated genes was performed using ClusterProfiler v4.16.0 [@yuClusterProfilerPackageComparing2012].

## Pseudobulk analysis of single cell RNA sequencing data

For pseudobulk analysis, the raw counts were aggregated across cells for each biological replicate on all MAIT cells using AggregateExpression using Seurat 5.3.0 [@hao2021] in R 4.5.1. Genes with a very low level of expression across biological replicates, less than 10 total counts across all samples, were filtered from the dataset. Differential gene expression analysis was performed using DESeq2 v1.48.2 [@love2014] on the aggregated raw counts, using default parameters, and not including a log2 fold change shrinkage step. The normalized counts were extracted from the DESeq2 object and used for visualization along be corresponding adjusted p-values and log2 fold changes. 

## TCR repertoire analysis 

TCR repertoire sequencing data were analyzed with the scRepertoire package v2.5.7 [@yangScRepertoire2Enhanced2024] in R 4.5.1. Starting with the filtered contig annotations output table from 'cellranger aggr', the createHTOContigList, combineTCR, and combineExpression functions were used for combining the TCR data from each sample and for integration of the combined TCR data with the corresponding Seurat object. We utilized the amino acid sequence of the paired CDR3 regions of the alpha and beta chains as the clonotype definition. T cell repertoire diversity was estimated using the D50 metric, which was calculated in R as the fraction of clonotypes, ordered by abundance, which account for 50 percent of total TCR sequences. Clonotype size was defined at the level of each biological replicate (Of all sequences: Rare: between 0% and 0.01%, Small: between 0.01% and 0.1%, Medium: between 0.1% and 1%, Large: between 1% and 10%, Hyperexpanded: between 10% and 100%). TCR overlap between mice was defined with the same clonotype definition: at level of the CDR3 amino acid region for the combined alpha and beta chains. TRBV-TRBJ parings were visualized using the package circlize [@gu2014].

## cNMF analysis

Consensus nonnegative matrix factorization [@kotliarIdentifyingGeneExpression2019] was performed using the tool made available by the original publication (https://github.com/dylkot/cNMF). THE input data consisted of the raw expression counts from all MAIT cells. The number of components to use was determined by running cNMF for a range of component numbers (from 3 to 20) and evaluating the resulting stability and error plots. Based on these plots, 15 components were selected for the final cNMF run. The resulting gene programs were annotated based on pathway enrichment analysis of the top 75 genes per program using ClusterProfiler v4.16.0 [@yuClusterProfilerPackageComparing2012].

## Differential abundance analysis

Differential abundance analysis of neighborhoods was performed using MiloR [@dannDifferentialAbundanceTesting2022]. 30 dimensions and 30 kNN were used for the construction of the KNN graph. Testing for differential abundance between conditions was performed using the 'testNhoods' function with the design formula ~ 0 + Groups, where 'Groups' indicates the experimental condition, a pairwise comparison between the *A. baumannii* and *F. tularensis* conditions were made using contrasts. Neighborhoods with an adjusted p value < 0.05 were considered differentially abundant and visualized on the UMAP representation and on a Leiden cluster basis. Additional details can be found in the corresponding section on the analysis code.

  