---
title: "Manuscript figures - patchwork"
---
```{r}
#| fig-width: 8
#| #| fig-height: 10

full_object_original |> names()
full_object_regressed |> names()
full_object_regressed$Milo_figures |> names()
full_object_regressed$cNMF_GEP_feature_plots |> names()
GEP_main_figure <- c(
    'GEP 1:\nActin filament organization',
    'GEP 2:\nT cell activation',
    'GEP 4:\nT cell differentiation',
    'GEP 8:\nCell migration',
    'GEP 10:\nCytotoxicity',
    'GEP 12:\nInterferon signaling'
)

p1 <- textGrob('Figure 2', gp = gpar(fontsize = 20, fontface = 'bold'))

full_object_regressed$cluster_heatmap2 <- full_object_regressed$cluster_heatmap +
    scale_y_discrete(labels = c('g1' = '1', 'g2' = '2', 'g3' = '3', 'g4' = '4', 'g5' = '5', 'g6' = '6', 'g7' = '7', 'g8' = '8', 'g9' = '9')) +    
     labs(x = 'Genes', y = 'Leiden clusters', title = 'Top 3 genes per cluster') 

# full_object_regressed$Milo_figures[['pathways']] <- full_object_regressed$Milo_figures[['pathways']] +
#     scale_size(range = c(1,5)) +
#     labs(title = 'MiloR: Neighborhood\nclusters - Pathway enrichment') +
#     scale_y_discrete(labels = label_wrap(45)) 

# full_object_regressed$Milo_figures$neighborhood_cluster_graph <- full_object_regressed$Milo_figures$neighborhood_cluster_graph +
#     labs(x = 'UMAP 1', y = 'UMAP 2', title = 'MiloR: Neighborhood\nclusters') + theme(legend.title = element_text(size = 8))  +
#     guides(fill = guide_legend(title = 'Clusters'))


plot_layout <- "
ABBB
"
row_one <- wrap_plots(list(full_object_regressed[['DimPlot']] ,
                            full_object_regressed[['DimPlot_groups']] 
                            ) ,
                            guides = 'collect', 
                            design = plot_layout) & 
                             guides(color = guide_legend(override.aes = list(size=2))) 
                            
 
row_milo <- wrap_plots(list(full_object_regressed$Milo_figures[['neighborhood_graph']] |> free(), 
                full_object_regressed$Milo_figures[['beeswarm_graph']] |> free(),
                plot_spacer() |> free()
                ), 
                # guides = 'collect',
                nrow = 1) +
                patchwork::plot_layout(widths = c(2, 1.5, 0.5))


row_feature_plots <- wrap_plots(list(
                full_object_regressed$feature_plots$Rorc |> free(),
                full_object_regressed$feature_plots$Tbx21  |> free(),
                full_object_regressed$feature_plots$Il17a  |> free(),
                full_object_regressed$feature_plots$Ifng |> free()
                ), nrow= 2)

row_GEP_feature_plots <- wrap_plots(list(
                full_object_regressed$cNMF_GEP_feature_plots$`GEP 1:\nActin filament organization` |> free(),
                full_object_regressed$cNMF_GEP_feature_plots$`GEP 2:\nT cell activation` |> free(),
                full_object_regressed$cNMF_GEP_feature_plots$`GEP 4:\nT cell differentiation` |> free(),
                full_object_regressed$cNMF_GEP_feature_plots$`GEP 8:\nCell migration` |> free(),
                full_object_regressed$cNMF_GEP_feature_plots$`GEP 10:\nCytotoxicity` |> free(),
                full_object_regressed$cNMF_GEP_feature_plots$`GEP 12:\nInterferon signaling` |> free()
                ), nrow= 2,  guides = 'collect')

row_signature_violins <- wrap_plots(list(
                full_object_regressed$signature_violin_plots$MAIT1  |> free(),
                full_object_regressed$signature_violin_plots$MAIT17 |> free()
                ), nrow= 2)

row_3 <- wrap_plots(list(
    row_feature_plots |> free(),
    row_signature_violins |> free(),
    row_GEP_feature_plots |> free()
    ), nrow = 1, widths = c(2, 0.8, 3) )
row_3

plot_layout <- "
    AAAABB
    CCCDDD
    EEEEEE
    EEEEEE
    GG####
    #####Z
    "
figure_2 <- wrap_plots(list(

                A = row_one |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)), 
                B = full_object_regressed[['cluster_frequency']] |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                C = full_object_regressed$cluster_heatmap2 |> free(), 
                D = row_milo |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                E = row_3  |> free()  & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),

#                 E = row_feature_plots |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                # F = row_GEP_feature_plots & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                # G = row_signature_violins |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                # H = 
                Z = wrap_elements(p1) |> free()
                ),# |> map(\(x) free(x, c('label'))),
                design = plot_layout) +
    plot_annotation(tag_levels = list(c('A', 'B', 'C', 'D', 'E', 'F', 'G', '', '', '', 'H', 'I', 'J', 'K', '', 'L', '', '', ''))) &
    theme_figures 

ggsave(plot = figure_2, filename = 'Figure_2.pdf', path = figures_path, width = 12, height = 14, units = 'in')
figure_2

```

## Figure S2

```{r}
#| fig-width: 8
#| fig-height: 10

p1 <- textGrob('Figure S2', gp = gpar(fontsize = 20, fontface = 'bold'))

plot_layout <- "
ABBB
"
row_one <- wrap_plots(list(full_object_original[['DimPlot']],
                            full_object_original[['DimPlot_groups']]),
                            guides = 'collect', 
                            design = plot_layout) & 
                             guides(color = guide_legend(override.aes = list(size=2))) 
 
row_signature <- wrap_plots(list(
                (full_object_original$signature_feature_plots$`Cycling G2M`+scale_color_continuous(palette = diverging_palette_3, breaks = c(-1, 0, 1)))  |> free(),
                full_object_original$signature_feature_plots$`Cycling S` |> free(),
                full_object_original$signature_violin_plots$`Cycling G2M`  |> free(),
                full_object_original$signature_violin_plots$`Cycling S`  |> free()
                ), nrow= 2)

row_pseudobulk <- wrap_plots(list(
                C =  full_object_original$volcano_plot |> free(), 
                D = row_signature |> free() 
                ), nrow = 1
                ) #|> map(\(x) free(x, 'space', side = 'rl')),

plot_layout <- "
    AAAABB
    CCCCCC
    CCCCCC
    FFGGHH
    DDEE#Z
    "
figure_S2 <- wrap_plots(list(
                A = row_one |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)), 
                B = full_object_original[['cluster_frequency']] |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                C = row_pseudobulk |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                F = full_object_original$pathways_Abau |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                G = full_object_original$pathways_Abau_Tcelldifferentiation |> free(),
                H = full_object_original$pathways_Abau_woundrepair |> free(),
                D = full_object_original$pathways_Ftula |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                E = full_object_original$pathways_Ftula_cytotoxicity |> free(),
                Z = wrap_elements(p1) |> free()
                ),# |> map(\(x) free(x, c('label'))),
                design = plot_layout) +
    plot_annotation(tag_levels = list(c('A', 'B', 'C', 'D', 'E', '', 'F', '', 'G', 'H', 'I', 'J', 'K', ''))) &
    theme_figures 
ggsave(plot = figure_S2, filename = 'Figure_S2.pdf', path = figures_path, width = 13, height = 13, units = 'in')
figure_S2

```


## Figure S3

```{r}
#| fig-width: 8
#| #| fig-height: 10

full_object_original |> names()
full_object_regressed |> names()
full_object_regressed$Milo_figures |> names()

p1 <- textGrob('Figure S3', gp = gpar(fontsize = 20, fontface = 'bold'))

# full_object_regressed |> walk(print)

# full_object_regressed$signature_feature_plots$tissue_repair

full_object_regressed$cluster_signatures <- full_object_regressed$cluster_signatures + scale_y_discrete(label = label_wrap(40))

row_feature_plots_2 <- wrap_plots(list(
                full_object_regressed$feature_plots$Gzmb |> free(),
                full_object_regressed$feature_plots$Gzmk |> free(),
                full_object_regressed$feature_plots$Slamf7 |> free(),
                full_object_regressed$feature_plots$Klrg1 |> free(),
                full_object_regressed$feature_plots$Ramp3 |> free(),
                full_object_regressed$feature_plots$Sdc1 |> free()
                ), nrow= 1) 

row_signature_heatmaps <- wrap_plots(list(
                full_object_regressed$signature_heatmaps2$MAIT1 |>  free(),
                full_object_regressed$signature_heatmaps2$MAIT17 |>  free(),
                full_object_regressed$signature_heatmaps2$`Cycling G2M` |>  free(),
                full_object_regressed$signature_heatmaps2$`Cycling S` |>  free()
                ), nrow= 1)

plot_layout <- "
    AAABBB
    AAABBB
    AAABBB
    CCCCCC
    DDDEEE
    FFFGGG
    "
figure_S3 <- wrap_plots(list(
                A = full_object_regressed$cluster_signatures |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)), 
                B = full_object_regressed$Milo_figures$pathways_genes |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                C = row_feature_plots_2 |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                D = full_object_regressed$signature_heatmaps$MAIT1 |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)), 
                E = full_object_regressed$signature_heatmaps$MAIT17 |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                F = full_object_regressed$signature_heatmaps$`Cycling G2M` |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                G = full_object_regressed$signature_heatmaps$`Cycling S` |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                # D = full_object_regressed$cluster_heatmap2 |> free(),
                # # E = row_feature_plots |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                # F =  row_signature_violins |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)), 
                # G = row_milo_neighborhoods |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                # H = 
                Z = wrap_elements(p1) |> free()
                ),# |> map(\(x) free(x, c('label'))),
                design = plot_layout) +
    plot_annotation(tag_levels = list(c('A', 'B', 'C', '', '', 'D', '', '', 'E', 'F', 'G', 'H'))) &
    theme_figures 
ggsave(plot = figure_S3, filename = 'Figure_S3.pdf', path = figures_path, width = 12, height = 14, units = 'in')
figure_S3

```

## Figure S4

```{r}
p1 <- textGrob('Figure S4', gp = gpar(fontsize = 20, fontface = 'bold'))

Ftula_object$DimPlot <- Ftula_object$DimPlot + labs(title = 'Ftula MAIT Leiden clusters')
Abau_object$DimPlot <- Abau_object$DimPlot + labs(title = 'Abau MAIT Leiden clusters')

Ftula_object$cluster_signatures <- Ftula_object$cluster_signatures + scale_y_discrete(label = label_wrap(30))
Ftula_object$cluster_heatmap <- Ftula_object$cluster_heatmap + 
    scale_y_discrete(labels = c('g1' = '1', 'g2' = '2', 'g3' = '3', 'g4' = '4', 'g5' = '5', 'g6' = '6', 'g7' = '7')) +    
     labs(x = 'Genes', y = 'Leiden clusters', title = 'Top 3 genes per cluster')

Abau_object$cluster_signatures <- Abau_object$cluster_signatures + scale_y_discrete(label = label_wrap(30))
Abau_object$cluster_heatmap <- Abau_object$cluster_heatmap + 
    scale_y_discrete(labels = c('g1' = '1', 'g2' = '2', 'g3' = '3', 'g4' = '4', 'g5' = '5', 'g6' = '6', 'g7' = '7', 'g8' = '8', 'g9' = '9', 'g10' = '10')) +    
     labs(x = 'Genes', y = 'Leiden clusters', title = 'Top 3 genes per cluster')

row_one <- wrap_plots(list(Ftula_object[['DimPlot']]  |> free(),
                        Ftula_object$cluster_heatmap  |> free()
                            ))+
                        plot_layout(widths = c(1, 2.5))

row_feature_plots <- wrap_plots(list(
                Ftula_object$feature_plots$Rorc |> free(),
                Ftula_object$feature_plots$Tbx21  |> free(),
                Ftula_object$feature_plots$Il17a  |> free(),
                Ftula_object$feature_plots$Ifng |> free(),
                Ftula_object$feature_plots$Gzmb |> free(),
                Ftula_object$feature_plots$Gzmk |> free(),
                Ftula_object$feature_plots$Slamf7 |> free(),
                Ftula_object$feature_plots$Klrg1 |> free()                
                ), nrow= 2)

row_two <- wrap_plots(list(Abau_object[['DimPlot']]  |> free(),
                        Abau_object$cluster_heatmap  |> free()
                            ))+
                        plot_layout(widths = c(1, 2.5))

row_feature_plots2 <- wrap_plots(list(
                Abau_object$feature_plots$Rorc |> free(),
                Abau_object$feature_plots$Tbx21  |> free(),
                Abau_object$feature_plots$Il17a  |> free(),
                Abau_object$feature_plots$Ifng |> free(),
                Abau_object$feature_plots$Ly6c2 |> free(),
                Abau_object$feature_plots$Ramp3 |> free(),
                Abau_object$feature_plots$Sdc1 |> free(),
                Abau_object$feature_plots$Areg |> free()                
                ), nrow= 2)


plot_layout <- "
    AAAABB
    CCCCBB
    CCCCBB
    DDDDEE
    FFFFEE
    FFFFEE
    "
figure_S4 <- wrap_plots(list(
                A = row_one |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)), 
                B = Ftula_object$cluster_signatures |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                C = row_feature_plots |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                D = row_two |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                E = Abau_object$cluster_signatures |>  free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                F = row_feature_plots2 |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                Z = wrap_elements(p1) |> free()
                ),# |> map(\(x) free(x, c('label'))),
                design = plot_layout) +
    plot_annotation(tag_levels = list(c('A', 'B', 'C', 'D', '', '', '', '', '', '', '', 'E', 'F', 'G', 'H', '', '', '', '', '', '', ''))) &
    theme_figures 
ggsave(plot = figure_S4, filename = 'Figure_S4.pdf', path = figures_path, width = 13, height = 13, units = 'in')
figure_S4
```

## Figure S5

```{r}
p1 <- textGrob('Figure S5', gp = gpar(fontsize = 20, fontface = 'bold'))

full_object_regressed$cNMF_GEP_pathways2 <- full_object_regressed$cNMF_GEP_pathways$plot +
    # scale_size(range = c(1,5)) +
    labs(title = 'cNMF: Gene expression program enriched GO terms', x = 'Gene expression programs (GEPs)') +
    scale_y_discrete(labels = label_wrap(45))

row_feature_plots <- wrap_plots(full_object_regressed$cNMF_GEP_feature_plots |> map(free), nrow= 4)
row_signatures <- wrap_plots(full_object_regressed$cNMF_GEP_violin_plots |> map(free), nrow= 4)

plot_layout <- "
    AAABBB
    AAABBB
    AAABBB
    CCC###
    CCC###
    CCC##Z
    "
figure_S5 <- wrap_plots(list(
                A = full_object_regressed$cNMF_GEP_pathways2 |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),  
                B = row_feature_plots |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                C = row_signatures |> free() & theme(axis.line = element_line(size = axis_thickness), axis.ticks = element_line(size = axis_thickness)),
                Z = wrap_elements(p1) |> free()
                ),# |> map(\(x) free(x, c('label'))),
                design = plot_layout) +
    plot_annotation(tag_levels = list(c('A', 'B', '', '', '', '', '', '', '', '', '', '', '', 'C', '', '', '', '', '', '', '', '', '', '', '', ''))) &
    theme_figures 
ggsave(plot = figure_S5, filename = 'Figure_S5.pdf', path = figures_path, width = 13, height = 13, units = 'in')
figure_S5
```